### ISSUE TITLE
低版本unity和urp 是否能够使用Unity 2020.3.25f1 + URP 10.x 

### ISSUE THREAD

**Issue by DKLouise** [killop/URP-12-Extension#1]

**Comment by killop** [comment]
每个版本适配的URP 版本都不一样，我这个是 unity 2021, 也建议你用这个版本

**Comment by DKLouise** [comment]
感谢
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年6月2日 16:14
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [killop/URP-12-Extension] 低版本unity和urp 是否能够使用Unity 2020.3.25f1 + URP 10.x  (Issue #1)
        
      
    
  

每个版本适配的URP 版本都不一样，我这个是 unity 2021, 也建议你用这个版本
